ruta_raíz:
  path:     /
  controller: 'funcionHomePage'
  methods:   [ GET ]

ruta_user_list:
  path:     /user/list/{json}
  controller: 'ListUsers'
  defaults:
    json: null
  methods:
    - GET

ruta_new_user:
  path:       /user/new
  controller: 'NewUser'
  methods:   [ GET, POST ]

ruta_delete_user:
  path:       /user/delete
  controller: 'DeleteUser'
  methods:   [ GET, POST ]

ruta_edit_user:
  path:       /user/edit
  controller: 'EditUser'
  methods:   [ GET, POST ]

ruta_user_edited:
  path:       /user/edited
  controller: 'UserEdited'
  methods:   [GET,POST]


