ruta_raíz:
  path:     /
  controller: 'funcionHomePage'
  methods:   [ GET ]

ruta_user_list:
  path:     /user/list/{json}
  controller: 'ListUsers'
  defaults:
    json: null
  methods:
    - GET

ruta_result_list:
  path:     /result/list/
  controller: 'ListResults'
  defaults:
    json: null
  methods:
    - GET
ruta_new_user:
  path:       /user/new
  controller: 'NewUser'
  methods:   [ GET, POST ]

ruta_new_result:
  path:       /result/new
  controller: 'NewResult'
  methods:   [ GET, POST ]

ruta_delete_user:
  path:       /user/delete
  controller: 'DeleteUser'
  methods:   [ GET, POST ]

ruta_delete_result:
  path:       /result/delete
  controller: 'DeleteResult'
  methods:   [ GET, POST ]

ruta_edit_user:
  path:       /user/edit
  controller: 'EditUser'
  methods:   [ GET, POST ]

ruta_user_edited:
  path:       /user/edited
  controller: 'UserEdited'
  methods: [ GET, POST ]

ruta_edit_result:
  path:       /result/edit
  controller: 'EditResult'
  methods:   [ GET, POST ]

ruta_result_edited:
  path:       /result/edited
  controller: 'ResultEdited'
  methods: [ GET, POST ]


